### ISSUE TITLE
Feature request: sync plugins and settings

### ISSUE THREAD

**Issue by tbdcit** [joshuakto/fit#13]
It would be nice to have the ability to also sync the plugin list and the settings between devices.

**Comment by hilsonp** [comment]
Thank you for your awesome work !

It would indeed be awesome to be able to sync settings...
Nevertheless, care must be taken because some settings should be local to a device or a "device type".

So far, I used Screwdriver plugin to export/import some settings and not others but would love to have a streamlined way to do this sync.

I might as well try to use the settings-profiles-obsidian-plugin together with the fit plugin but:

- I have to test if the profiles can be stored inside the vault or if they must reside outside the vault. 
- settings-profiles-obsidian-plugin does not currently work on mobile

This let me think that fit could sync settings with a second git repo dedicated to obsidian settings, using different branches.
This way, I could:
- have a "desktop" branch in my settings git repo
- have another "mobile" branch in my settings git repo
- be able to merge things between branches on github if I like

The interresting point with settings-profiles-obsidian-plugin is the possibility to combine a global settings with some device specific settings.

Hopefully this give you some ideas or let you test the collaboration of fit with other plugins like settings-profiles-obsidian-plugin.
