### ISSUE TITLE
Feature request - Help with merge

### ISSUE THREAD

**Issue by hilsonp** [joshuakto/fit#16]
For those like me searching a way to manage merge of sync conflict working on a phone, here is a plugin that can help:
https://github.com/friebetill/obsidian-file-diff

We could submit a PR to this project to have a command to manage "conflict files" stored under _fit as it does with syncthings...
... or we could have an option in "fit" to deal with conflicts like syncthings does.

In the mean time, hopefuly this plugin helps.

**Comment by joshuakto** [comment]
Thank you for suggesting this feature @hilsonp
I think this will be a fairly involved feature as I envision it will involve the following steps

1. adding a UI button to turn auto merge on-or-off
2. Incorporate the file-diff algorithm and merge when there's no conflict
3. have a fallback mechanism for the sync to proceed when there is merge conflict
  a.  put the conflicting changes in _fit folder
  b. notify users of the conflict
4. Implement testing for this feature (testing is not setup in this repo yet but since this function if implemented incorrectly will corrupt user's files I think such testing would be needed)

If anyone would like to make a PR for this feature, I would be happy to review it and merge it once the feature is well tested

**Comment by hilsonp** [comment]
Nice to hear from you @joshuakto !!!

Unfortunatelly, after my first successful tests with fit, I wanted to use it with my real vault that has a few hundreds of files and fit just did not manage it (at least on my iPhone).
I thought the project was a one shot and "dead" (no blame) so I did not persued.
If you want me to invest trying to reproduce and open an issue, just let me know.
