### ISSUE TITLE
Support sync settings and plugins

### ISSUE THREAD

**Issue by rootknight** [joshuakto/fit#8]
Thanks your work😀 
it works fine for me，but i have many plugins，Whether  consider supporting settings and plugins sync？
Thanks again for your work！

**Comment by joshuakto** [comment]
Thanks for the suggestion! Since this plugin universally supports mobile and desktop devices, it would be difficult to sync plugins as many are not supported on mobile.
Support for plugin and settings sync would warrant a different plugin, if you are interested in developing such plugin, I would suggest you to look into how the [BRAT plugin](https://tfthacker.com/BRAT) managers and install plugins.

**Comment by metruzanca** [comment]
> it would be difficult to sync plugins as many are not supported on mobile.

I understand that you want to support mobile, however, I believe what @rootknight is asking is simply to include the .obsidian folder in the sync. That way, you can sync your vault's configuration, theme and plugins across devices.

That being said, I don't see code that is explicitly ignoring the `.obsidian` folder when you pull, so is it a limitation of obsidian's plugin api that prevents access to .obsidian?

I know `obsidian-git` is able to, so theoretically it should be possible.. maybe you just need a different command to make changes to `.obsidian`.

---

If you'd like I can help with this feature.
